"""Abstract repository interface for Admin Panel users."""
from typing import Protocol
from uuid import UUID
from admin.src.domain.users.entities import AdminUser, AdminRole


class IAdminUserRepository(Protocol):
    async def get_by_id(self, id: UUID) -> AdminUser | None: ...
    async def get_by_email(self, email: str) -> AdminUser | None: ...
    async def list_all(self) -> list[AdminUser]: ...
    async def save(self, user: AdminUser) -> AdminUser: ...
    async def delete(self, id: UUID) -> None: ...
    async def count_all(self) -> int: ...
    async def count_by_role(self, role: AdminRole) -> int: ...
