"""Abstract repository interface for break-glass access requests."""
from typing import Protocol
from uuid import UUID

from backend.src.domain.break_glass.entities import BreakGlassAccess


class IBreakGlassAccessRepository(Protocol):
    async def get_by_id(self, request_id: UUID) -> BreakGlassAccess | None: ...
    async def add(self, request: BreakGlassAccess) -> BreakGlassAccess: ...
    async def save(self, request: BreakGlassAccess) -> BreakGlassAccess: ...
    async def list_needing_review(self) -> list[BreakGlassAccess]: ...
