"""Abstract repository interface for lab orders."""
from typing import Protocol
from uuid import UUID

from backend.src.domain.lab_orders.entities import LabOrder


class ILabOrderRepository(Protocol):
    async def get_by_id(self, lab_order_id: UUID) -> LabOrder | None: ...
    async def add(self, lab_order: LabOrder) -> LabOrder: ...
    async def save(self, lab_order: LabOrder) -> LabOrder: ...
    async def list_by_encounter_id(self, encounter_id: UUID) -> list[LabOrder]: ...
