"""Abstract repository interfaces for auth entities."""
from typing import Protocol
from uuid import UUID
from admin.src.domain.auth.entities import AdminSession, AdminInvitation


class IAdminSessionRepository(Protocol):
    async def get_by_token(self, token: str) -> AdminSession | None: ...
    async def save(self, session: AdminSession) -> AdminSession: ...
    async def invalidate(self, token: str) -> None: ...


class IAdminInvitationRepository(Protocol):
    async def get_by_token(self, token: str) -> AdminInvitation | None: ...
    async def get_by_email(self, email: str) -> AdminInvitation | None: ...
    async def save(self, invitation: AdminInvitation) -> AdminInvitation: ...
    async def revoke(self, id: UUID) -> None: ...
