"""hospital domain schema

Revision ID: ad778436d69b
Revises: v2w3x4y5z6a7
Create Date: 2026-07-05 20:38:57.693809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad778436d69b'
down_revision: Union[str, Sequence[str], None] = 'v2w3x4y5z6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('next_of_kin_name', sa.String(length=200), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=30), nullable=True),
    sa.Column('insurance_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('esi_level', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_entity_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_glass_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requesting_user_id', sa.UUID(), nullable=False),
    sa.Column('target_patient_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('ordered_by', sa.UUID(), nullable=False),
    sa.Column('test_type', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_payload', sa.Text(), nullable=True),
    sa.Column('fulfilled_by', sa.UUID(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('ordered_by', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('dosage', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dispensed_by', sa.UUID(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('bp_systolic', sa.Integer(), nullable=False),
    sa.Column('bp_diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse', sa.Integer(), nullable=False),
    sa.Column('respiratory_rate', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('esi_suggested_level', sa.Integer(), nullable=False),
    sa.Column('esi_level', sa.Integer(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id')
    )
    # SaaS-only tables being retired. `tickets` <-> `chat_sessions` (and
    # `agents` <-> `agent_versions`) are circular FKs, so plain op.drop_table
    # can't order them; CASCADE resolves the whole graph in one pass. Postgres
    # drops each table's own indexes automatically, so no separate
    # op.drop_index calls are needed.
    _saas_tables = (
        "agent_knowledge_base",
        "chat_sessions",
        "rules",
        "integration_agent_links",
        "agents",
        "numbers",
        "knowledge_base_entries",
        "widgets",
        "ticket_summaries",
        "knowledge_bases",
        "evaluation_conversation_logs",
        "evaluations",
        "tickets",
        "evaluation_tools",
        "scenarios",
        "integrations",
        "api_tools",
        "agent_versions",
        "tags",
        "conversation_logs",
        "agent_api_tools",
    )
    for _table in _saas_tables:
        op.execute(f"DROP TABLE IF EXISTS {_table} CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_api_tools',
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attached_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_api_tools_agent_id_fkey')),
    sa.ForeignKeyConstraint(['api_tool_id'], ['api_tools.id'], name=op.f('agent_api_tools_api_tool_id_fkey')),
    sa.PrimaryKeyConstraint('agent_id', 'api_tool_id', name=op.f('agent_api_tools_pkey'))
    )
    op.create_table('conversation_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('speaker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_start_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_end_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spoken_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.CheckConstraint('chat_session_id IS NOT NULL OR ticket_id IS NOT NULL', name=op.f('ck_conversation_logs_session_or_ticket')),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_conversation_logs_chat_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('conversation_logs_ticket_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_logs_pkey'))
    )
    op.create_index(op.f('ix_conversation_logs_chat_session_id'), 'conversation_logs', ['chat_session_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('tags_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    sa.UniqueConstraint('department_id', 'value', name=op.f('uq_tags_department_id_value'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tags_department_id'), 'tags', ['department_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('changes_applied', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('change_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_versions_agent_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_versions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_versions_pkey')),
    sa.UniqueConstraint('agent_id', 'version_number', name=op.f('uq_agent_versions_agent_id_version_number'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('api_tools',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('http_method', sa.VARCHAR(length=10), server_default=sa.text("'GET'::character varying"), autoincrement=False, nullable=False),
    sa.Column('endpoint_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('auth_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('api_tools_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('api_tools_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('api_tools_pkey')),
    sa.UniqueConstraint('department_id', 'name', name=op.f('uq_api_tools_department_id_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('credentials_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('integrations_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('integrations_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('integrations_pkey')),
    sa.UniqueConstraint('department_id', 'provider', name=op.f('uq_integrations_department_id_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_integrations_webhook_secret'), 'integrations', ['webhook_secret'], unique=True)
    op.create_index(op.f('ix_integrations_department_id'), 'integrations', ['department_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('scenarios_agent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scenarios_pkey'))
    )
    op.create_table('evaluation_tools',
    sa.Column('evaluation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_tool_id'], ['api_tools.id'], name=op.f('evaluation_tools_api_tool_id_fkey')),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('evaluation_tools_evaluation_id_fkey')),
    sa.PrimaryKeyConstraint('evaluation_id', 'api_tool_id', name=op.f('evaluation_tools_pkey'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('interface_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('from_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('assigned_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_details', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('tickets_agent_id_fkey')),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('tickets_agent_version_id_fkey')),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_tickets_chat_session_id_chat_sessions')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('tickets_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_pkey')),
    sa.UniqueConstraint('reference', name=op.f('uq_tickets_reference'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tickets_chat_session_id'), 'tickets', ['chat_session_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('eval_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('max_steps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_speaker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('welcome_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('simulated_user_persona', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agent_variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('judge_criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tool_mock_responses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('ai_judge_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('per_criterion_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('steps_taken', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('evaluations_agent_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('evaluations_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('evaluations_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluations_pkey'))
    )
    op.create_table('evaluation_conversation_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('evaluation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('speaker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_start_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_end_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spoken_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('evaluation_conversation_logs_evaluation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluation_conversation_logs_pkey'))
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('knowledge_bases_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('knowledge_bases_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_bases_pkey'))
    )
    op.create_table('ticket_summaries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('general_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('journey', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avg_agent_latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_user_latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_routing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_summaries_ticket_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_summaries_pkey')),
    sa.UniqueConstraint('ticket_id', name=op.f('ticket_summaries_ticket_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('widgets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('widget_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('launcher_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('first_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain_allowlist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], name=op.f('widgets_assigned_agent_id_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('widgets_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('widgets_pkey')),
    sa.UniqueConstraint('widget_id', name=op.f('widgets_widget_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('knowledge_base_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('indexing_status', sa.VARCHAR(length=20), server_default=sa.text("'processing'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('knowledge_base_entries_created_by_fkey')),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name=op.f('knowledge_base_entries_knowledge_base_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_base_entries_pkey'))
    )
    op.create_table('numbers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('number_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('provisioned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], name=op.f('numbers_assigned_agent_id_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('numbers_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('numbers_pkey')),
    sa.UniqueConstraint('phone_number', name=op.f('numbers_phone_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'inactive'::character varying"), autoincrement=False, nullable=False),
    sa.Column('brand_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('personalization_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deployed_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('agents_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('agents_department_id_fkey')),
    sa.ForeignKeyConstraint(['deployed_version_id'], ['agent_versions.id'], name=op.f('fk_agents_deployed_version_id_agent_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('agents_pkey')),
    sa.UniqueConstraint('department_id', 'name', name=op.f('uq_agents_department_id_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('integration_agent_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('integration_agent_links_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('integration_agent_links_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('integration_agent_links_department_id_fkey')),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('integration_agent_links_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_agent_links_pkey')),
    sa.UniqueConstraint('agent_id', name=op.f('uq_integration_agent_links_agent_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_integration_agent_links_integration_id'), 'integration_agent_links', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_agent_links_department_id'), 'integration_agent_links', ['department_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('rules_agent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rules_pkey'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('widget_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('conversation_state', sa.VARCHAR(length=40), server_default=sa.text("'in_progress'::character varying"), autoincrement=False, nullable=False),
    sa.Column('close_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('chat_sessions_agent_id_fkey')),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('chat_sessions_agent_version_id_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('chat_sessions_department_id_fkey')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('chat_sessions_ticket_id_fkey')),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], name=op.f('chat_sessions_widget_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_sessions_pkey'))
    )
    op.create_index(op.f('ix_chat_sessions_ticket_id'), 'chat_sessions', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_department_id'), 'chat_sessions', ['department_id'], unique=False)
    op.create_table('agent_knowledge_base',
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attached_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_knowledge_base_agent_id_fkey')),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name=op.f('agent_knowledge_base_knowledge_base_id_fkey')),
    sa.PrimaryKeyConstraint('agent_id', 'knowledge_base_id', name=op.f('agent_knowledge_base_pkey'))
    )
    op.drop_table('triage_records')
    op.drop_table('prescriptions')
    op.drop_table('lab_orders')
    op.drop_table('clinical_notes')
    op.drop_table('break_glass_access')
    op.drop_table('audit_logs')
    op.drop_table('inventory_items')
    op.drop_table('encounters')
    op.drop_table('patients')
    # ### end Alembic commands ###
