"""Abstract repository interface for prescriptions."""
from typing import Protocol
from uuid import UUID

from backend.src.domain.prescriptions.entities import Prescription


class IPrescriptionRepository(Protocol):
    async def get_by_id(self, prescription_id: UUID) -> Prescription | None: ...
    async def add(self, prescription: Prescription) -> Prescription: ...
    async def save(self, prescription: Prescription) -> Prescription: ...
    async def list_by_encounter_id(self, encounter_id: UUID) -> list[Prescription]: ...
