"""Abstract repository interface for inventory items."""
from typing import Protocol
from uuid import UUID

from backend.src.domain.inventory.entities import InventoryItem


class IInventoryItemRepository(Protocol):
    async def get_by_id(self, item_id: UUID) -> InventoryItem | None: ...
    async def add(self, item: InventoryItem) -> InventoryItem: ...
    async def save(self, item: InventoryItem) -> InventoryItem: ...
    async def list_by_department_id(self, department_id: UUID) -> list[InventoryItem]: ...
